version: 2.1
defaults: &defaults
  working_directory: ~/full-stack
  environment:
    # Configure the JVM and Gradle to avoid OOM errors
    _JAVA_OPTIONS: "-Xmx3g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    CC_TEST_REPORTER_ID: "8850fc04f1134b9f6852e7405bf94ca55fbf22dc16620015bac22ffe2230abe3"
  docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
    - image: circleci/node:10.16.3

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/full-stack/tmp
      - run:
          name: Run backend tests
          command: |
            chmod +x gradlew
            ./gradlew test
            ./tmp/cc-test-reporter format-coverage -t jacoco -o tmp/codeclimate.backend.xml build/customJacocoReportDir/test/jacocoTestReport.xml
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.backend.json
  frontend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/full-stack/tmp
      - run: yarn install
      - run:
          name: Run frontend testss
          command: |
            yarn test -- --coverage
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/frontend/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.frontend.json
  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: YOUR_REPO_CC_TEST_REPORTER_ID
    steps:
      - attach_workspace:
          at: ~/full-stack/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - frontend-tests:
          requires:
            - build
      - upload-coverage:
          requires:
            - backend-tests
            - frontend-tests